# Generated by Django 5.2.4 on 2025-07-02 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('location', models.CharField(max_length=100, verbose_name='Local')),
                ('date', models.DateTimeField(verbose_name='Data e Hora do Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_admin', to='accounts.adminprofile')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventregistration_event', to='events.event', verbose_name='Evento')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventregistration_student', to='accounts.studentprofile', verbose_name='Estudante')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('event', 'student')},
            },
        ),
    ]
